name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  VERSION: "1.0.${{ github.run_number }}"
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Update package version
      run: npm version ${{ env.VERSION }} --no-git-tag-version

    - name: Build package
      run: npm run build

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish

    - name: Set Version Git Tag
      run: |
        git tag ${{ env.VERSION }}
        git push origin ${{ env.VERSION }}